### ISSUE TITLE
ng g @ngneat/transloco:join does not work on the example

### ISSUE THREAD

**Issue by kabomi** [itayod/transloco-files-management#1]
Any clues why it does not work out of the box. Thanks

**Comment by itayod** [comment]
This is just an example app for handling i18n file :)
But, if you want the `join` command to work here it will work after the following actions:
1. run `$ npm run transloco:extract-scoped-libs`
2. run `$ ng g @ngneat/transloco:join --default-lang en`

for further information about `join` please [see](https://netbasal.gitbook.io/transloco/schematics/join)
